//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 05:52:46 PM CEST 
//


package it.gdsoftware.scontrino.xml70.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DispositivoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispositivoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tipo" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}TipoDispositivoType"/>
 *         &lt;element name="IdDispositivo" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}IdDispositivoType"/>
 *         &lt;element name="GeoLocalizzazione" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}GeoLocType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispositivoType", namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0", propOrder = {
    "tipo",
    "idDispositivo",
    "geoLocalizzazione"
})
public class DispositivoType {

    @XmlElement(name = "Tipo", required = true)
    protected TipoDispositivoType tipo;
    @XmlElement(name = "IdDispositivo", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String idDispositivo;
    @XmlElement(name = "GeoLocalizzazione")
    protected GeoLocType geoLocalizzazione;

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDispositivoType }
     *     
     */
    public TipoDispositivoType getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDispositivoType }
     *     
     */
    public void setTipo(TipoDispositivoType value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the idDispositivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdDispositivo() {
        return idDispositivo;
    }

    /**
     * Sets the value of the idDispositivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdDispositivo(String value) {
        this.idDispositivo = value;
    }

    /**
     * Gets the value of the geoLocalizzazione property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocType }
     *     
     */
    public GeoLocType getGeoLocalizzazione() {
        return geoLocalizzazione;
    }

    /**
     * Sets the value of the geoLocalizzazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocType }
     *     
     */
    public void setGeoLocalizzazione(GeoLocType value) {
        this.geoLocalizzazione = value;
    }

}
