//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 05:52:46 PM CEST 
//


package it.gdsoftware.scontrino.xml70.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TotaliType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TotaliType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroDocCommerciali" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}ProgressivoPrelievoType"/>
 *         &lt;element name="PagatoContanti" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="PagatoElettronico" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="ScontoApagare" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="Ticket" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}TicketType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotaliType", namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0", propOrder = {
    "numeroDocCommerciali",
    "pagatoContanti",
    "pagatoElettronico",
    "scontoApagare",
    "ticket"
})
public class TotaliType {

    @XmlElement(name = "NumeroDocCommerciali")
    protected long numeroDocCommerciali;
    @XmlElement(name = "PagatoContanti")
    protected BigDecimal pagatoContanti;
    @XmlElement(name = "PagatoElettronico")
    protected BigDecimal pagatoElettronico;
    @XmlElement(name = "ScontoApagare")
    protected BigDecimal scontoApagare;
    @XmlElement(name = "Ticket")
    protected TicketType ticket;

    /**
     * Gets the value of the numeroDocCommerciali property.
     * 
     */
    public long getNumeroDocCommerciali() {
        return numeroDocCommerciali;
    }

    /**
     * Sets the value of the numeroDocCommerciali property.
     * 
     */
    public void setNumeroDocCommerciali(long value) {
        this.numeroDocCommerciali = value;
    }

    /**
     * Gets the value of the pagatoContanti property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPagatoContanti() {
        return pagatoContanti;
    }

    /**
     * Sets the value of the pagatoContanti property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPagatoContanti(BigDecimal value) {
        this.pagatoContanti = value;
    }

    /**
     * Gets the value of the pagatoElettronico property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPagatoElettronico() {
        return pagatoElettronico;
    }

    /**
     * Sets the value of the pagatoElettronico property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPagatoElettronico(BigDecimal value) {
        this.pagatoElettronico = value;
    }

    /**
     * Gets the value of the scontoApagare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getScontoApagare() {
        return scontoApagare;
    }

    /**
     * Sets the value of the scontoApagare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setScontoApagare(BigDecimal value) {
        this.scontoApagare = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link TicketType }
     *     
     */
    public TicketType getTicket() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketType }
     *     
     */
    public void setTicket(TicketType value) {
        this.ticket = value;
    }

}
