//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 05:52:46 PM CEST 
//


package it.gdsoftware.scontrino.xml70.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VentilazioneIVAType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VentilazioneIVAType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VentilazioneIVAType", namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0")
@XmlEnum
public enum VentilazioneIVAType {


    /**
     * Indica l'eventuale applicazione della ventilazione dell'IVA sui corrispettivi (ex DM 3495 del 24/02/1973)
     * 
     */
    SI;

    public String value() {
        return name();
    }

    public static VentilazioneIVAType fromValue(String v) {
        return valueOf(v);
    }

}
