//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.12 at 11:50:47 PM CET 
//


package it.gdsoftware.scontrino.xml70.core;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DatiRegistratoriTelematiciType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiRegistratoriTelematiciType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="IVA" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}IVAType"/>
 *           &lt;element name="Natura" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}NaturaType"/>
 *           &lt;element name="VentilazioneIVA" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}VentilazioneIVAType"/>
 *         &lt;/choice>
 *         &lt;element name="Ammontare" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType"/>
 *         &lt;element name="RifNormativo" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}String100LatinType" minOccurs="0"/>
 *         &lt;element name="ImportoParziale" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType"/>
 *         &lt;element name="TotaleAmmontareResi" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="TotaleAmmontareAnnulli" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="BeniInSospeso" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="NonRiscossoServizi" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="NonRiscossoFatture" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="TotaleDaFattureRT" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="NonRiscossoDCRaSSN" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="NonRiscossoOmaggio" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Amount2DecimalType" minOccurs="0"/>
 *         &lt;element name="CodiceAttivita" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0}Integer6Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiRegistratoriTelematiciType", namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0", propOrder = {
    "iva",
    "natura",
    "ventilazioneIVA",
    "ammontare",
    "rifNormativo",
    "importoParziale",
    "totaleAmmontareResi",
    "totaleAmmontareAnnulli",
    "beniInSospeso",
    "nonRiscossoServizi",
    "nonRiscossoFatture",
    "totaleDaFattureRT",
    "nonRiscossoDCRaSSN",
    "nonRiscossoOmaggio",
    "codiceAttivita"
})
public class DatiRegistratoriTelematiciType {

    @XmlElement(name = "IVA")
    protected IVAType iva;
    @XmlElement(name = "Natura")
    protected NaturaType natura;
    @XmlElement(name = "VentilazioneIVA")
    protected VentilazioneIVAType ventilazioneIVA;
    @XmlElement(name = "Ammontare", required = true)
    protected BigDecimal ammontare;
    @XmlElement(name = "RifNormativo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rifNormativo;
    @XmlElement(name = "ImportoParziale", required = true)
    protected BigDecimal importoParziale;
    @XmlElement(name = "TotaleAmmontareResi")
    protected BigDecimal totaleAmmontareResi;
    @XmlElement(name = "TotaleAmmontareAnnulli")
    protected BigDecimal totaleAmmontareAnnulli;
    @XmlElement(name = "BeniInSospeso")
    protected BigDecimal beniInSospeso;
    @XmlElement(name = "NonRiscossoServizi")
    protected BigDecimal nonRiscossoServizi;
    @XmlElement(name = "NonRiscossoFatture")
    protected BigDecimal nonRiscossoFatture;
    @XmlElement(name = "TotaleDaFattureRT")
    protected BigDecimal totaleDaFattureRT;
    @XmlElement(name = "NonRiscossoDCRaSSN")
    protected BigDecimal nonRiscossoDCRaSSN;
    @XmlElement(name = "NonRiscossoOmaggio")
    protected BigDecimal nonRiscossoOmaggio;
    @XmlElement(name = "CodiceAttivita")
    protected Integer codiceAttivita;

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link IVAType }
     *     
     */
    public IVAType getIVA() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVAType }
     *     
     */
    public void setIVA(IVAType value) {
        this.iva = value;
    }

    /**
     * Gets the value of the natura property.
     * 
     * @return
     *     possible object is
     *     {@link NaturaType }
     *     
     */
    public NaturaType getNatura() {
        return natura;
    }

    /**
     * Sets the value of the natura property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturaType }
     *     
     */
    public void setNatura(NaturaType value) {
        this.natura = value;
    }

    /**
     * Gets the value of the ventilazioneIVA property.
     * 
     * @return
     *     possible object is
     *     {@link VentilazioneIVAType }
     *     
     */
    public VentilazioneIVAType getVentilazioneIVA() {
        return ventilazioneIVA;
    }

    /**
     * Sets the value of the ventilazioneIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link VentilazioneIVAType }
     *     
     */
    public void setVentilazioneIVA(VentilazioneIVAType value) {
        this.ventilazioneIVA = value;
    }

    /**
     * Gets the value of the ammontare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmmontare() {
        return ammontare;
    }

    /**
     * Sets the value of the ammontare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmmontare(BigDecimal value) {
        this.ammontare = value;
    }

    /**
     * Gets the value of the rifNormativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRifNormativo() {
        return rifNormativo;
    }

    /**
     * Sets the value of the rifNormativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRifNormativo(String value) {
        this.rifNormativo = value;
    }

    /**
     * Gets the value of the importoParziale property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImportoParziale() {
        return importoParziale;
    }

    /**
     * Sets the value of the importoParziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImportoParziale(BigDecimal value) {
        this.importoParziale = value;
    }

    /**
     * Gets the value of the totaleAmmontareResi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaleAmmontareResi() {
        return totaleAmmontareResi;
    }

    /**
     * Sets the value of the totaleAmmontareResi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaleAmmontareResi(BigDecimal value) {
        this.totaleAmmontareResi = value;
    }

    /**
     * Gets the value of the totaleAmmontareAnnulli property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaleAmmontareAnnulli() {
        return totaleAmmontareAnnulli;
    }

    /**
     * Sets the value of the totaleAmmontareAnnulli property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaleAmmontareAnnulli(BigDecimal value) {
        this.totaleAmmontareAnnulli = value;
    }

    /**
     * Gets the value of the beniInSospeso property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBeniInSospeso() {
        return beniInSospeso;
    }

    /**
     * Sets the value of the beniInSospeso property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBeniInSospeso(BigDecimal value) {
        this.beniInSospeso = value;
    }

    /**
     * Gets the value of the nonRiscossoServizi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonRiscossoServizi() {
        return nonRiscossoServizi;
    }

    /**
     * Sets the value of the nonRiscossoServizi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonRiscossoServizi(BigDecimal value) {
        this.nonRiscossoServizi = value;
    }

    /**
     * Gets the value of the nonRiscossoFatture property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonRiscossoFatture() {
        return nonRiscossoFatture;
    }

    /**
     * Sets the value of the nonRiscossoFatture property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonRiscossoFatture(BigDecimal value) {
        this.nonRiscossoFatture = value;
    }

    /**
     * Gets the value of the totaleDaFattureRT property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotaleDaFattureRT() {
        return totaleDaFattureRT;
    }

    /**
     * Sets the value of the totaleDaFattureRT property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotaleDaFattureRT(BigDecimal value) {
        this.totaleDaFattureRT = value;
    }

    /**
     * Gets the value of the nonRiscossoDCRaSSN property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonRiscossoDCRaSSN() {
        return nonRiscossoDCRaSSN;
    }

    /**
     * Sets the value of the nonRiscossoDCRaSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonRiscossoDCRaSSN(BigDecimal value) {
        this.nonRiscossoDCRaSSN = value;
    }

    /**
     * Gets the value of the nonRiscossoOmaggio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonRiscossoOmaggio() {
        return nonRiscossoOmaggio;
    }

    /**
     * Sets the value of the nonRiscossoOmaggio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonRiscossoOmaggio(BigDecimal value) {
        this.nonRiscossoOmaggio = value;
    }

    /**
     * Gets the value of the codiceAttivita property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodiceAttivita() {
        return codiceAttivita;
    }

    /**
     * Sets the value of the codiceAttivita property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodiceAttivita(Integer value) {
        this.codiceAttivita = value;
    }

}
