//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.12 at 11:50:47 PM CET 
//


package it.gdsoftware.scontrino.xml70.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Blocco con informazioni sui dati contabili e fiscali dei corrispettivi
 * 
 * <p>Java class for PeriodoInattivoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodoInattivoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dal" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Al" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodoInattivoType", namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/corrispettivi/dati/v1.0", propOrder = {
    "dal",
    "al"
})
public class PeriodoInattivoType {

    @XmlElement(name = "Dal", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dal;
    @XmlElement(name = "Al", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar al;

    /**
     * Gets the value of the dal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDal() {
        return dal;
    }

    /**
     * Sets the value of the dal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDal(XMLGregorianCalendar value) {
        this.dal = value;
    }

    /**
     * Gets the value of the al property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAl() {
        return al;
    }

    /**
     * Sets the value of the al property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAl(XMLGregorianCalendar value) {
        this.al = value;
    }

}
